build_commands: []
environment_variables: {}
external_package_dirs: []
model_metadata: {}
model_name: basten_sdxl_text_2_image
python_version: py310
requirements:
  - --extra-index-url https://download.pytorch.org/whl/cu121
  - torch==2.3.0
  - torchvision==0.18.0
  - opencv-python-headless==4.10.0.84
  - diffusers==0.28.0
  - accelerate==0.30.1
  - transformers==4.41.1
  - albumentations==1.4.11
  - imageio==2.34.1
  - kornia==0.7.3
  - timm==1.0.7
  - peft==0.9.0
  - prettytable==3.6.0
  - safetensors==0.4.3
  - matplotlib==3.9.1
  - boto3==1.34.148
  - numpy==1.26.4
  - httpx==0.27.0
resources:
  accelerator: null
  cpu: '16'
  memory: 20Gi
  use_gpu: true
secrets: {}
system_packages:
  - libgl1-mesa-glx
  - libglib2.0-0
